const fs = require('fs');
const path = require('path');

const databaseUrl = process.env.DATABASE_URL;
const outPath = path.join(__dirname, '..', '.env');

if (!databaseUrl) {
  console.error('DATABASE_URL not found in environment.');
  console.error('Usage (PowerShell):');
  console.error('  $env:DATABASE_URL = "postgres://user:pass@host:port/db"; npm run env:save');
  console.error('Or set it inline (POSIX): DATABASE_URL="..." npm run env:save');
  process.exit(1);
}

const content = `# Generated by scripts/save-env.js
DATABASE_URL=${JSON.stringify(databaseUrl)}\n`;

try {
  fs.writeFileSync(outPath, content, { encoding: 'utf8', flag: 'w' });
  console.log(`Wrote .env to ${outPath}`);
  console.log('You can now run the server and it will load DATABASE_URL from .env');
} catch (err) {
  console.error('Failed to write .env:', err);
  process.exit(1);
}
